# Generated by Django 5.0.7 on 2025-02-14 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('loan_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_credits', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_debits', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('usd', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('gbp', models.DecimalField(decimal_places=2, default=1.23, max_digits=10)),
                ('eur', models.DecimalField(decimal_places=2, default=1.03, max_digits=10)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_balance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
