# Generated by Django 5.0.7 on 2025-02-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_exchange_loanrequest_resetpassword_transfercode_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_password',
            field=models.CharField(blank=True, help_text='Password or PIN for the card', max_length=128, null=True),
        ),
    ]
