# Generated by Django 5.0.7 on 2025-02-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_card_card_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('savings', 'Savings'), ('current', 'Current'), ('fixed', 'Fixed Deposit')], default='savings', help_text='Type of bank account (e.g., Savings, Current, Fixed Deposit)', max_length=20),
        ),
    ]
