# Generated by Django 5.0.7 on 2025-02-15 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_transaction_reference_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('TNX', models.CharField(blank=True, help_text='Transaction reference or ID', max_length=100, null=True)),
                ('network', models.CharField(blank=True, help_text='Network used for the deposit (e.g., Ethereum, Bitcoin)', max_length=50, null=True)),
                ('rate', models.DecimalField(decimal_places=2, default=1.0, help_text='Exchange rate at the time of deposit', max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
