# Generated by Django 5.0.7 on 2025-02-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_deposit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('Ethereum', 'Ethereum'), ('Bitcoin', 'Bitcoin'), ('USDT', 'USDT')], help_text='The network for which this deposit address applies.', max_length=50, unique=True)),
                ('deposit_address', models.CharField(help_text='The deposit address for the given network.', max_length=255)),
                ('qr_code', models.ImageField(blank=True, help_text='Optional QR code for the deposit address.', null=True, upload_to='payment_gateways/')),
                ('instructions', models.TextField(blank=True, help_text='Additional instructions for deposits on this network.', null=True)),
            ],
            options={
                'verbose_name': 'Payment Gateway',
                'verbose_name_plural': 'Payment Gateways',
            },
        ),
    ]
