# Generated by Django 5.0.7 on 2025-02-16 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_paymentgateway'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_admin',
        ),
    ]
