# Generated by Django 5.0.7 on 2025-02-16 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_transfercode_created_at_transfercode_expires_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountbalance',
            name='usd',
        ),
    ]
