# Generated by Django 5.0.7 on 2025-02-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_accountbalance_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbalance',
            name='eur',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='gbp',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
