# Generated by Django 5.0.7 on 2025-02-17 09:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_accountbalance_eur_alter_accountbalance_gbp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanrequest',
            name='type',
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='approval_date',
            field=models.DateTimeField(blank=True, help_text='Date and time when the loan was approved', null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Administrator who approved the loan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='collateral',
            field=models.TextField(blank=True, help_text='Collateral details (if any)', null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='currency',
            field=models.CharField(default='USD', help_text='Currency of the loan (e.g., USD, EUR, GBP)', max_length=10),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='disbursement_date',
            field=models.DateTimeField(blank=True, help_text='Date and time when the funds were disbursed', null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual interest rate (%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='loan_type',
            field=models.CharField(default='personal', help_text='Type of loan (e.g., personal, home, auto)', max_length=50),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='outstanding_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Remaining balance to be repaid', max_digits=12),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='processing_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Fee charged for processing the loan', max_digits=12),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='repayment_start_date',
            field=models.DateField(blank=True, help_text='Date when repayment starts', null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='status_detail',
            field=models.CharField(blank=True, help_text='Additional details about the loan status', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='term_months',
            field=models.PositiveIntegerField(blank=True, help_text='Loan term in months', null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount requested', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='date',
            field=models.DateTimeField(auto_now_add=True, help_text='Date when the request was made'),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', help_text='Current status of the loan request', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='user',
            field=models.ForeignKey(help_text='User who requested the loan', on_delete=django.db.models.deletion.CASCADE, related_name='loan_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
