# Generated by Django 5.0.7 on 2025-02-17 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_loanrequest_type_loanrequest_approval_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanrequest',
            name='outstanding_balance',
        ),
        migrations.RemoveField(
            model_name='loanrequest',
            name='processing_fee',
        ),
    ]
