# Generated by Django 5.0.7 on 2025-02-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_loanrequest_outstanding_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eur_usd', models.DecimalField(decimal_places=4, help_text='Exchange rate from EUR to USD', max_digits=10)),
                ('gbp_usd', models.DecimalField(decimal_places=4, help_text='Exchange rate from GBP to USD', max_digits=10)),
                ('eur_gbp', models.DecimalField(decimal_places=4, help_text='Exchange rate from EUR to GBP', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update')),
            ],
        ),
    ]
