# Generated by Django 5.0.7 on 2025-02-17 22:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_exchangerate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='expects',
        ),
        migrations.RemoveField(
            model_name='exchange',
            name='paid',
        ),
        migrations.AddField(
            model_name='exchange',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Exchanged amount', max_digits=12),
        ),
        migrations.AddField(
            model_name='exchange',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date and time of the exchange'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchange',
            name='from_currency',
            field=models.CharField(default=django.utils.timezone.now, help_text='USD', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchange',
            name='to_currency',
            field=models.CharField(default=django.utils.timezone.now, help_text='EUR', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exchange',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the exchange', max_length=100),
        ),
    ]
