# Generated by Django 5.0.7 on 2025-02-18 09:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_exchange_expects_remove_exchange_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resetpassword',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resetpassword',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resetpassword',
            name='reset_code',
            field=models.CharField(max_length=32),
        ),
    ]
