# Generated by Django 5.0.7 on 2025-02-24 21:51

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_resetpassword_created_at_resetpassword_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='expiry_date',
            field=models.DateField(default=accounts.models.default_expiry_date, help_text='Expiry date (2 years after purchase)'),
        ),
    ]
