# Generated by Django 5.0.7 on 2025-02-25 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_card_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='bank_country',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='bank_holder',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='identifier_code',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='sender_name',
        ),
        migrations.AlterField(
            model_name='transfer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=255)),
                ('swift_code', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='transfer',
            name='beneficiary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='accounts.beneficiary'),
        ),
    ]
