# Generated by Django 5.0.7 on 2025-02-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_transfer_bank_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
