# Generated by Django 5.0.7 on 2025-02-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_account_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbalance',
            name='checking_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
