# Generated by Django 5.0.7 on 2025-02-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_accountbalance_checking_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='account',
            field=models.CharField(choices=[('Savings_Account', 'Savings Account'), ('Checking_Account', 'Checking Account')], default='Savings_Account', help_text='The account selected for deposit', max_length=50),
        ),
    ]
