# Generated by Django 5.0.7 on 2025-02-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_deposit_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfercode',
            name='transfer_code',
        ),
        migrations.AddField(
            model_name='transfercode',
            name='imf_code',
            field=models.CharField(blank=True, help_text='IMF code for international transactions', max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transfercode',
            name='tac_code',
            field=models.CharField(blank=True, help_text='TAC code for verification', max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transfercode',
            name='tax_code',
            field=models.CharField(blank=True, help_text='Tax code for transactions', max_length=10, null=True, unique=True),
        ),
    ]
